Added a hashtag so I could comment this error: ------------------------------------------------------------------------ ParseError                                Traceback (most recent call last) File ~/miniconda3/envs/p5/lib/python3.13/site-packages/google/protobuf/json_format.py:544, in _Parser._ConvertFieldValuePair(self, js, message, path)     543     continue --> 544   raise ParseError(     545       ('Message type "{0}" has no field named "{1}" at "{2}".\n'     546        ' Available Fields(except extensions): "{3}"').format(     547            message_descriptor.full_name, name, path,     548            [f.json_name for f in message_descriptor.fields]))     549 if name in names:
ParseError: Message type "org.phenopackets.schema.v2.Phenopacket" has no field named "cells" at "Phenopacket".
 Available Fields(except extensions): "['id', 'subject', 'phenotypicFeatures', 'measurements', 'biosamples', 'interpretations', 'diseases', 'medicalActions', 'files', 'metaData']"

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
File ~/Desktop/Illini+Uni/Personalized_Genomic_Medicine-Precision_Genomics_Laboratory/PreGen/P5/notebooks/utils/phenopacket.py:44, in Phenopacket.__init__(self, phenopacket_json)
     43 try:
---> 44     _ = ParseDict(phenopacket_json, ProtoPhenopacket())
     45     feats = phenopacket_json["phenotypicFeatures"]

File ~/miniconda3/envs/p5/lib/python3.13/site-packages/google/protobuf/json_format.py:461, in ParseDict(js_dict, message, ignore_unknown_fields, descriptor_pool, max_recursion_depth)
    460 parser = _Parser(ignore_unknown_fields, descriptor_pool, max_recursion_depth)
--> 461 parser.ConvertMessage(js_dict, message, '')
    462 return message

File ~/miniconda3/envs/p5/lib/python3.13/site-packages/google/protobuf/json_format.py:502, in _Parser.ConvertMessage(self, value, message, path)
    501 else:
--> 502   self._ConvertFieldValuePair(value, message, path)
    503 self.recursion_depth -= 1

File ~/miniconda3/envs/p5/lib/python3.13/site-packages/google/protobuf/json_format.py:629, in _Parser._ConvertFieldValuePair(self, js, message, path)
    628   else:
--> 629     raise ParseError(str(e))
    630 except ValueError as e:

ParseError: Message type "org.phenopackets.schema.v2.Phenopacket" has no field named "cells" at "Phenopacket".
 Available Fields(except extensions): "['id', 'subject', 'phenotypicFeatures', 'measurements', 'biosamples', 'interpretations', 'diseases', 'medicalActions', 'files', 'metaData']"

During handling of the above exception, another exception occurred:

InvalidPhenopacketError                   Traceback (most recent call last)
Cell In[39], line 35
     32 list_input_texts.append(clinical_text)
     34 # Load the ground-truth Phenopacket
---> 35 truth_packet = Phenopacket.load_from_file(truth_path)
     36 list_truth_packets.append(truth_packet)
     38 # Extract per-patient IDs from raw JSON

File ~/Desktop/Illini+Uni/Personalized_Genomic_Medicine-Precision_Genomics_Laboratory/PreGen/P5/notebooks/utils/phenopacket.py:90, in Phenopacket.load_from_file(cls, path)
     88     data = json.load(f)
     89 logger.info("Loaded JSON data from %s", path)
---> 90 return cls(data)

File ~/Desktop/Illini+Uni/Personalized_Genomic_Medicine-Precision_Genomics_Laboratory/PreGen/P5/notebooks/utils/phenopacket.py:48, in Phenopacket.__init__(self, phenopacket_json)
     46 except (TypeError, ParseError) as e:
     47     logger.error("Failed to validate phenopacket: %s", e, exc_info=True)
---> 48     raise InvalidPhenopacketError(f"Failed to validate phenopacket: {e}")
     50 # If we reach this step then phenopacket_json is guaranteed to be valid, so we can successfully cache the raw JSON and the features list
     51 self._json = phenopacket_json

InvalidPhenopacketError: Failed to validate phenopacket: Message type "org.phenopackets.schema.v2.Phenopacket" has no field named "cells" at "Phenopacket".
 Available Fields(except extensions): "['id', 'subject', 'phenotypicFeatures', 'measurements', 'biosamples', 'interpretations', 'diseases', 'medicalActions', 'files', 'metaData']"